apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtinder-backend
  labels:
    app: devtinder-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devtinder-backend
  template:
    metadata:
      labels:
        app: devtinder-backend
    spec:
      containers:
        - name: backend
          image: vamsikrishna212/devtinder-be:v1
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal:27017/devtinder"
