apiVersion: v1
kind: Service
metadata:
  name: devtinder-backend-svc
  labels:
    app: devtinder-backend
spec:
  selector:
    app: devtinder-backend
  ports:
    - protocol: TCP
      port: 5000      # exposed service port
      targetPort: 5000
  type: ClusterIP     # internal only
